// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCatAflrFGokfJb2nY5rzZ4Pe2tCnou020',
    appId: '1:784146564294:web:47b9498fb63d282a6603c7',
    messagingSenderId: '784146564294',
    projectId: 'to-do-list-cdc0f',
    authDomain: 'to-do-list-cdc0f.firebaseapp.com',
    storageBucket: 'to-do-list-cdc0f.appspot.com',
    measurementId: 'G-LQ37VMK1JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQrhSwYUo-yMEjEz2jtuiIvi1KAPjl9aU',
    appId: '1:784146564294:android:c477b82a022d41fc6603c7',
    messagingSenderId: '784146564294',
    projectId: 'to-do-list-cdc0f',
    storageBucket: 'to-do-list-cdc0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD400ajlezGhP4rmJPwv189kQuHOIsXkxc',
    appId: '1:784146564294:ios:a4e7852f4689f5056603c7',
    messagingSenderId: '784146564294',
    projectId: 'to-do-list-cdc0f',
    storageBucket: 'to-do-list-cdc0f.appspot.com',
    iosBundleId: 'com.example.baseTodolist',
  );
}
